name: backEnd API server CI
on:
  pull_request:
    branches: [BE/release, dev, main]

permissions:
  contents: read

jobs:
  api-server-ci:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ 코드 체크아웃
        uses: actions/checkout@v3

      - name : 👻 노드 설정
        uses : actions/setup-node@v3
        with:
          node-version: '20'

      - name: ⬇️ 의존성 설치
        working-directory: ./backEnd/api
        run: npm install

      - name: ✅ 유닛 테스트
        working-directory: ./backEnd/api
        run: npm test

      - name: 📦 프로젝트 빌드
        working-directory: ./backEnd/api
        run: npm run build